"""Adicionado o campo currency em person

Revision ID: 08db4faa9f4d
Revises: 8bbb6dc77ef8
Create Date: 2022-09-21 19:20:23.208723

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "08db4faa9f4d"
down_revision = "8bbb6dc77ef8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "person",
        sa.Column(
            "currency",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
            server_default="USD",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("person", "currency")
    # ### end Alembic commands ###
