"""
initial

Revision ID: 8bbb6dc77ef8
Revises: aaa
Create Date: 2022-09-21 19:15:53.764218

"""

# revision identifiers, used by Alembic.
revision = "8bbb6dc77ef8"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
